name: 'setup-docker'
description: Setting up docker
inputs:
  docker-user:
    required: true
    description: Docker hub User
  docker-password:
    required: true
    description: Docker Hub Password
runs:
  using: 'composite'
  steps:
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      if: ${{ github.event_name == 'release' }}
      with:
        username: ${{ inputs.docker-user }}
        password: ${{ inputs.docker-password }}
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-